import numpy as np
import pandas as pd
import os
os.environ["ECCODES_MESSAGES_QUIET"] = "1"
import xarray as xr
from scipy.ndimage import gaussian_filter

## Dictionary of valid bounds for plots.make_plot.
## Generated by Claude Sonnet 4.6
map_sectors = {
    "CONUS":            (24,  -125,  50,  -66),
    "Eastern US":       (24,  -105,  50,  -66),
    "Alaska":           (51,  -180,  72, -129),
    "Hawaii":           (18,  -161,  23, -154),
    "North America":    (15,  -170,  75,  -50),
    "Northeast US":     (37,   -82,  48,  -66),
    "Southeast US":     (24,   -92,  37,  -75),
    "Central US":       (30,  -105,  50,  -85),
    "Southern Plains":  (25,  -105,  37,  -90),
    "Northern Plains":  (40,  -110,  50,  -95),
    "Northwest US":     (41,  -125,  50, -110),
    "Southwest US":     (31,  -125,  41, -109),
    "Gulf Coast":       (24,   -98,  34,  -80),
    "Great Lakes":      (40,   -93,  48,  -75),
    "Central America":  ( 7,   -93,  18,  -77),
    "Pacific Coast":    (32,  -130,  50, -115),
    "Canada":           (49,  -141,  84,  -52),
    "Mexico":           (14,  -118,  33,  -86),
    "Global":           (-90, -180,  90,  180),

    # Regional
    "NYC Metro":          (40,   -75,  42,  -72),
    "Upstate NY":         (41,   -79,  44,  -74),
    "New England":        (41,   -74,  48,  -67),

    # Tropical Cyclone Domains
    "North Atlantic":     (0,    -100,  60,  -10), 
    "Caribbean":          (9,    -88,   24,  -59),  
    "Gulf of Mexico":     (18,   -98,   31,  -80),
    "SW Atlantic":        (23,   -80,   35,  -60),   
    "Atlantic MDR":       (10,   -80,   20,  -20),   
    "E Pacific":          (5,    -140,  35, -100),
    "C Pacific":          (5,    -180,  35, -140),
    "W Pacific":          (5,     100,  40,  180),
    "N Indian Ocean":     (0,     50,   25,   100),

    # SPECIAL
    "Special":            (57, -150, 62, -142)
}

## Dictionary of variable keys for NCEP models
## Values are lists of [Herbie key, plot routine]
ncep_key = {
    "gh500": ["HGT:500 mb", "height"],
    "wind500": ["GRD:500 mb", "wind"],
    "temp500": ["TMP:500 mb", "temp"]
}

model_fullname = {
    "GFS": "Global Forecast System (GFS)",
    "NAM": "North American Model (NAM)",
    "HRRR": "High-Resolution Rapid Refresh (HRRR)",
}

def KtoF(temps):
    C = temps - 273.15
    F = ((9/5)*C) + 32
    return F


def d_dy(f):
    """
    Compute the derivative of f with respect to y.
    
    Parameters:
    f : xarray.DataArray
        The gridded variable with dimensions ['lat', 'lon'].
        
    Returns:
    dfdy : xarray.DataArray
        The derivative of f with respect to y.
    """
    # On a sphere, one degree of latitude is equal to approximately 111 kilometers
    y_dist = 111 * 1000                       # meters
    dfdy = f.differentiate('latitude') / y_dist
    
    return dfdy

def d_dx(f):
    """
    Compute the derivative of f with respect to x.
    
    Parameters:
    f : xarray.DataArray
        The gridded variable with dimensions ['lat', 'lon'].
        
    Returns:
    dfdx : xarray.DataArray
        The derivative of f with respect to x.
    """
    # One degree of longitude is a function of latitude, and
    # equal to 111 kilometers times the cosine of latitude.
    x_dist = 111 * 1000 * np.cos(2 * np.pi / 360 * f['latitude'])            # meters
    dfdx = f.differentiate('longitude') / x_dist

    return dfdx

def calc_geostrophic_wind(Z):
    """
    Calculate the geostrophic wind components (u_g, v_g) from the geopotential height field.

    Parameters
    ----------
    Z : xarray.DataArray
        Geopotential height [m], defined on pressure levels with 
        dimensions including latitude and longitude.

    Returns
    -------
    ug, vg : xarray.DataArray
        The zonal (ug) and meridional (vg) components of the geostrophic wind [m/s].
        Values are masked outside the latitude band 10°–75° (both hemispheres) to 
        avoid issues near the equator (f → 0) and polar regions.

    Notes
    -----
    - The geopotential is defined as φ = gZ, where g is the gravitational acceleration.
    - The geostrophic balance is given by:
      
        ug = -(1/f) * ∂φ/∂y  
        vg =  (1/f) * ∂φ/∂x  

      where f = 2Ω sin(φ) is the Coriolis parameter, and (x, y) are local 
      eastward and northward directions respectively.
    - Requires global fields of latitude and longitude on a regular grid.
    """
    Omega = (2 * np.pi * (1 / 86400))                   # angular velocity of Earth
    f = 2 * Omega * np.sin(np.deg2rad(Z['latitude']))   # s^-1
    ug = -d_dy(9.81 * Z) / f
    vg = d_dx(9.81 * Z) / f
    ug = ug.where((np.abs(Z['latitude']) > 5) & (np.abs(Z['latitude']) < 80))
    vg = vg.where((np.abs(Z['latitude']) > 5) & (np.abs(Z['latitude']) < 80))
    return ug, vg

def smooth_var(F, smooth_fac):
    sigma = np.zeros(len(F.shape))
    sigma[-2:] = smooth_fac
    Z_smooth = xr.DataArray(data = gaussian_filter(F.data, sigma = sigma),
                        dims = F.dims, coords = F.coords)
    return Z_smooth




import s3fs
import datetime 
import urllib
import tempfile
import gzip
aws = s3fs.S3FileSystem(anon=True)

import logging
logging.getLogger("cfgrib").setLevel(logging.ERROR)

def get_radar_files(datestring):
    try:
        data_files = aws.ls(f'noaa-mrms-pds/ALASKA/ReflectivityAtLowestAltitude_00.50/{datestring}/', refresh=True) 
        ptype_files = aws.ls(f'noaa-mrms-pds/ALASKA/PrecipFlag_00.00/{datestring}/', refresh=True)
        print("Found files!")
    except Exception as e:
        print(f"Error accessing files from AWS: {e}")
    return data_files, ptype_files

def get_radar_data(data_files, ptype_files, i):
        logging.getLogger("cfgrib").setLevel(logging.ERROR)
        try:
            most_recent_file = data_files[i]
            response = urllib.request.urlopen(f"https://noaa-mrms-pds.s3.amazonaws.com/{most_recent_file[14:]}")
            compressed_file = response.read()

            with tempfile.NamedTemporaryFile(suffix=".grib2") as f:
                f.write(gzip.decompress(compressed_file))
                f.flush()
                data = xr.load_dataarray(f.name, engine="cfgrib", decode_timedelta=True)

            most_recent_file = ptype_files[i]
            response = urllib.request.urlopen(f"https://noaa-mrms-pds.s3.amazonaws.com/{most_recent_file[14:]}")
            compressed_file = response.read()

            with tempfile.NamedTemporaryFile(suffix=".grib2") as f:
                f.write(gzip.decompress(compressed_file))
                f.flush()
                precip_type = xr.load_dataarray(f.name, engine="cfgrib", decode_timedelta=True)
        except Exception as e:
            print(f"Something went wrong when trying to read the data:\n {e}")
            raise ValueError("Error reading data files in.")
        
        return data, precip_type

    